'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CusHome

    '''<summary>
    '''lnkDeposit0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDeposit0 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTransfer As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPayment As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkNewAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNewAcc As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkModify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkModify As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvViewAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvViewAll As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvCheAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCheAcc As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvSavAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSavAcc As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvIRAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvIRAS As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvStoPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvStoPor As Global.System.Web.UI.WebControls.GridView
End Class
